// ─── DHH ARTIST ROSTER ─────────────────────────────────────────────
// Album/cover data now lives in albums-data.js (real iTunes catalog,
// generated by tools/fetch_covers.py + tools/fetch_targeted.py).

export const ARTISTS = [
  { name: "DIVINE",        city: "MUMBAI",     since: 2011, note: "Gully rap pioneer. From Andheri East to global stages." },
  { name: "KR$NA",         city: "NEW DELHI",  since: 2006, note: "Technical precision. Battle-tested. Two decades deep." },
  { name: "SEEDHE MAUT",   city: "NEW DELHI",  since: 2017, note: "Encore ABJ × Calm. The sharpest duo in the subcontinent." },
  { name: "MC STAN",       city: "PUNE",       since: 2018, note: "Auto-tuned melancholy. Changed the sound of the streets." },
  { name: "RAFTAAR",       city: "NEW DELHI",  since: 2008, note: "Flow technician. Mentor to a full generation." },
  { name: "EMIWAY BANTAI", city: "MUMBAI",     since: 2013, note: "Independent to the bone. 20M subscribers, zero labels." },
  { name: "PRABH DEEP",    city: "NEW DELHI",  since: 2015, note: "Punjabi noir. Azadi Records' first flagbearer." },
  { name: "TALHA ANJUM",   city: "KARACHI",    since: 2012, note: "Young Stunners. Urdu rap's most-streamed voice." },
  { name: "HANUMANKIND",   city: "BENGALURU",  since: 2019, note: "Big Dawgs heard worldwide. Kerala to the Billboard 100." },
  { name: "NAEZY",         city: "MUMBAI",     since: 2014, note: "The original Gully Boy. Started on an iPad." },
  { name: "FARIS SHAFI",   city: "LAHORE",     since: 2011, note: "Satirical, fearless, untouchable pen." },
  { name: "EVA B",         city: "LYARI",      since: 2019, note: "Masked voice of Lyari. Broke every ceiling rapping in Balochi-Urdu." },
];
